name: CI (alpha)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/gitpod-satysfi
      TAG: 0.1.0-alpha
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./alpha
          push: false
          load: true
          tags: ${{ env.REPOSITORY_NAME }}:${{ env.TAG }}
          cache-from: type=gha,scope=${{ env.TAG }}
          cache-to: type=gha,mode=max,scope=${{ env.TAG }}

      - name: Run test
        run: docker run --rm ${{ env.REPOSITORY_NAME }}:${{ env.TAG }} satysfi --help

      - name: Push to Docker Hub
        run: docker push ${{ env.REPOSITORY_NAME }}:${{ env.TAG }}
        if: github.event_name != 'pull_request'
