name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ocaml-version: 4.12.1
            satysfi-version: 0.0.6
            satyrographos-version: 0.0.2.11
          - ocaml-version: 4.12.1
            satysfi-version: 0.0.7
            satyrographos-version: 0.0.2.11
    env:
      IMAGE_NAME: gitpod-satysfi
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.satysfi-version }}
          build-args: |
            OCAML_VERSION=${{ matrix.ocaml-version }}
            SATYSFI_VERSION=${{ matrix.satysfi-version }}
            SATYROGRAPHOS_VERSION=${{ matrix.satyrographos-version }}
          cache-from: type=gha,scope=${{ matrix.satysfi-version }}
          cache-to: type=gha,mode=max,scope=${{ matrix.satysfi-version }}

      - name: Run test
        run: docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.satysfi-version }} satysfi --help

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.satysfi-version }}
        if: github.event_name != 'pull_request'
